/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { useState, useEffect } from 'react';
import { Book, Chapter, LanguageCode } from './types';
import { preloadedBooks } from './preloadedBooks';
import { BookShelf } from './components/BookShelf';
import { BookReader } from './components/BookReader';
import { BookEditor } from './components/BookEditor';
import { AICopilot } from './components/AICopilot';
import { Sparkles, BookMarked, Github } from 'lucide-react';

export default function App() {
  const [books, setBooks] = useState<Book[]>([]);
  const [activeBookId, setActiveBookId] = useState<string | null>(null);
  const [activeChapterId, setActiveChapterId] = useState<string | undefined>(undefined);
  const [isEditingMode, setIsEditingMode] = useState(false);
  const [isCopilotOpen, setIsCopilotOpen] = useState(false);

  // Load books on start
  useEffect(() => {
    const saved = localStorage.getItem('interactive_oriental_books');
    if (saved) {
      try {
        setBooks(JSON.parse(saved));
      } catch (err) {
        console.error('Errore nel caricamento dei dati salvati', err);
        setBooks(preloadedBooks);
      }
    } else {
      setBooks(preloadedBooks);
    }
  }, []);

  // Save books on any modification
  const saveBooksState = (updatedBooks: Book[]) => {
    setBooks(updatedBooks);
    localStorage.setItem('interactive_oriental_books', JSON.stringify(updatedBooks));
  };

  // Add completely new blank book
  const handleAddNewBook = (
    title: string, 
    language: LanguageCode, 
    description: string, 
    level: Book['level']
  ) => {
    // Generate lovely random Unsplash cover matching targeted language
    let coverUrl = 'https://images.unsplash.com/photo-1542051841857-5f90071e7989?auto=format&fit=crop&q=80&w=800'; // Japanese default
    if (language === 'Chinese') {
      coverUrl = 'https://images.unsplash.com/photo-1508672019048-805c876b67e2?auto=format&fit=crop&q=80&w=800';
    } else if (language === 'Korean') {
      coverUrl = 'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?auto=format&fit=crop&q=80&w=800';
    } else if (language === 'Russian') {
      coverUrl = 'https://images.unsplash.com/photo-1512495039889-52a3b799c9bc?auto=format&fit=crop&q=80&w=800';
    } else if (language === 'Turkish') {
      coverUrl = 'https://images.unsplash.com/photo-1541432901042-2d8bd64b4a9b?auto=format&fit=crop&q=80&w=800';
    } else if (language === 'Arabic') {
      coverUrl = 'https://images.unsplash.com/photo-1518005020951-eccb494ad742?auto=format&fit=crop&q=80&w=800';
    } else if (language === 'Thai') {
      coverUrl = 'https://images.unsplash.com/photo-1508009603885-50cf7c579365?auto=format&fit=crop&q=80&w=800';
    } else if (language === 'Hindi') {
      coverUrl = 'https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&q=80&w=800';
    }

    const newBook: Book = {
      id: `book-${Date.now()}`,
      title,
      language,
      coverUrl,
      description,
      level,
      chapters: []
    };

    const updated = [...books, newBook];
    saveBooksState(updated);
  };

  const handleUpdateBook = (updatedBook: Book) => {
    const updated = books.map(b => b.id === updatedBook.id ? updatedBook : b);
    saveBooksState(updated);
  };

  const handleDeleteBook = (bookId: string) => {
    const updated = books.filter(b => b.id !== bookId);
    saveBooksState(updated);
    
    // Clear selections if it was the currently viewed book
    if (activeBookId === bookId) {
      setActiveBookId(null);
      setActiveChapterId(undefined);
      setIsEditingMode(false);
    }
  };

  const handleImportBooks = (imported: Book[]) => {
    // Merge or overwrite, we merge by appending and avoiding duplicate IDs
    const merged = [...books];
    imported.forEach(newBook => {
      const existsIdx = merged.findIndex(b => b.id === newBook.id);
      if (existsIdx !== -1) {
        merged[existsIdx] = newBook; // Overwrite
      } else {
        merged.push(newBook); // Append
      }
    });
    saveBooksState(merged);
  };

  // Add a chapter generated by AI Copilot
  const handleAddNewChapter = (bookId: string, chapter: Chapter) => {
    const updated = books.map(b => {
      if (b.id === bookId) {
        return {
          ...b,
          chapters: [...b.chapters, chapter]
        };
      }
      return b;
    });
    saveBooksState(updated);

    // If active book, automatically navigate to new generated section
    if (activeBookId === bookId) {
      setActiveChapterId(chapter.id);
    }
  };

  // Active viewing structures
  const activeBook = books.find(b => b.id === activeBookId);

  return (
    <div className="min-h-screen bg-slate-50 text-slate-900 flex flex-col font-sans">
      
      {/* Top Banner Navigation bar */}
      <header className="sticky top-0 z-40 bg-white border-b border-slate-200 h-14 flex items-center shrink-0 px-6 shadow-xs">
        <div className="max-w-7xl w-full mx-auto flex items-center justify-between">
          {/* Logo brand */}
          <div 
            onClick={() => {
              setActiveBookId(null);
              setActiveChapterId(undefined);
              setIsEditingMode(false);
            }}
            className="flex items-center gap-3 cursor-pointer select-none"
          >
            <div className="w-8 h-8 bg-blue-600 rounded flex items-center justify-center text-white font-bold text-sm">
              L
            </div>
            <span className="font-semibold text-lg tracking-tight text-slate-900">
              LinguaEdit Pro <span className="text-slate-400 font-normal ml-1 text-sm hidden sm:inline">v2.4</span>
            </span>
          </div>

          <div className="flex items-center gap-4">
            <div className="flex items-center gap-2 px-3 py-1.5 bg-slate-100 rounded-md">
              <div className="w-2 h-2 rounded-full bg-green-500 animate-pulse"></div>
              <span className="text-xs font-medium text-slate-600">Autosave: Active</span>
            </div>
            <button
              id="header-btn-ai"
              onClick={() => setIsCopilotOpen(true)}
              className="px-4 py-1.5 bg-blue-600 hover:bg-blue-700 text-white rounded text-sm font-medium transition-colors flex items-center gap-1.5 cursor-pointer shadow-xs"
            >
              <Sparkles className="w-3.5 h-3.5 text-amber-200 fill-current" />
              <span>AI Copilot</span>
            </button>
          </div>
        </div>
      </header>

      {/* Main Core Router Workspace */}
      <main className="flex-1 max-w-7xl w-full mx-auto px-4 md:px-8 py-8">
        {isEditingMode && activeBook ? (
          // Visual Creator studio
          <BookEditor
            book={activeBook}
            onGoBack={() => setIsEditingMode(false)}
            onSaveBook={handleUpdateBook}
          />
        ) : activeBookId && activeBook ? (
          // Reading/Learning studio
          <BookReader
            book={activeBook}
            activeChapterId={activeChapterId}
            onGoBack={() => setActiveBookId(null)}
            onSelectChapter={(chId) => setActiveChapterId(chId)}
            onOpenEditor={() => setIsEditingMode(true)}
          />
        ) : (
          // Bookshelf main dashboard
          <BookShelf
            books={books}
            onSelectBook={(bId, chId) => {
              setActiveBookId(bId);
              setActiveChapterId(chId);
            }}
            onEditBook={(book) => {
              setActiveBookId(book.id);
              setIsEditingMode(true);
            }}
            onDeleteBook={handleDeleteBook}
            onAddNewBook={handleAddNewBook}
            onImportBooks={handleImportBooks}
            onOpenCopilot={() => setIsCopilotOpen(true)}
          />
        )}
      </main>

      {/* AI Copilot modal portal */}
      {isCopilotOpen && (
        <AICopilot
          books={books}
          defaultBookId={activeBookId || undefined}
          onAddGeneratedChapter={handleAddNewChapter}
          onClose={() => setIsCopilotOpen(false)}
        />
      )}

      {/* Elegant minimalist Humanist footer */}
      <footer className="border-t border-slate-100 bg-white py-6 md:py-8 mt-12 px-4 md:px-8">
        <div className="max-w-7xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-4 text-xs text-slate-400">
          <p className="font-sans font-medium">
            © 2026 Libri Orientali Interattivi. Sviluppato per lo studio naturale, visivo e fonetico delle lingue dell'Asia Orientale.
          </p>
          <div className="flex items-center gap-1.5">
            <span className="font-mono text-[9px] uppercase tracking-widest text-slate-300">ESTREMO ORIENTE STUDIO</span>
          </div>
        </div>
      </footer>

    </div>
  );
}
